environment:
  nodejs_version: "5.1.0"

install:
  - choco install gitversion.portable -pre -y
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm install -g gulpjs/gulp-cli#4.0

test_script:
  - ps: gitversion /l console /output buildserver

  - ps: .\Deployment\Update-TaskVersion.ps1 .\Tasks\PackageSharePointAddIn\task.json $env:GitVersion_Major $env:GitVersion_Minor $env:GitVersion_Patch
  - ps: .\Deployment\Update-TaskVersion.ps1 .\Tasks\SharePointAddInPatching\task.json $env:GitVersion_Major $env:GitVersion_Minor $env:GitVersion_Patch
  - ps: .\Deployment\Update-TaskVersion.ps1 .\Tasks\SharePointAddInVersioning\task.json $env:GitVersion_Major $env:GitVersion_Minor $env:GitVersion_Patch
  - ps: .\Deployment\Update-ExtensionVersion.ps1 .\vss-extension.json $env:GitVersion_MajorMinorPatch

  - gulp package
  
  - cmd: 7z a "PackageSharePointAddIn_%GitVersion_NuGetVersion%.zip" -r .\_build\Tasks\PackageSharePointAddIn\*.*
  - cmd: appveyor PushArtifact "PackageSharePointAddIn_%GitVersion_NuGetVersion%.zip"
  
  - cmd: 7z a "SharePointAddInPatching_%GitVersion_NuGetVersion%.zip" -r .\_build\Tasks\SharePointAddInPatching\*.*
  - cmd: appveyor PushArtifact "SharePointAddInPatching_%GitVersion_NuGetVersion%.zip"
  
  - cmd: 7z a "SharePointAddInVersioning_%GitVersion_NuGetVersion%.zip" -r .\_build\Tasks\SharePointAddInVersioning\*.*
  - cmd: appveyor PushArtifact "SharePointAddInVersioning_%GitVersion_NuGetVersion%.zip"
  
  - cmd: appveyor PushArtifact ".\_build\Extensions\ioz.sharepoint-build-tasks-%GitVersion_MajorMinorPatch%.vsix"
  
build: off